mac_linux_task:
  matrix:
    - container:
        image: node:latest

    - macos_instance:
        image: big-sur-base
      dep_script: brew install node && npm install --global yarn

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: chmod +x setup_env.sh && . setup_env.sh && yarn postinstall && yarn electron:build

  environment:
    GH_TOKEN: ENCRYPTED[1ac94c5ed2bfdc350487c348f6084d4fe2bfb7686174040835b82526ae5def5c88cf844c31005eae618cdcffe4dc409f]
    YOUTUBECLIENTID: ENCRYPTED[bc5553108e4d239739413525ec9f13f2d8c33b1a1f7d3d9f658f7b17746fce3d76b00d79a26b0d2552f6ad3dbf78a7ef]
